# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 0.0.1
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"

# This section and its corresponding dependencies are only for beta testers
for:
version: 0.0.2
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"

version: 0.0.3
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"

version: 0.0.4
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"

version: 0.0.4
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"

version: 0.0.5
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"

for:
  every_iteration:
                 pass:
version: 0.1.0
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"

if:
  def():
      above:
           iteration=true:
                         pass:
version: 0.1.1
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"                       

def():
      above:
           iteration=true:
                         pass:
version: 0.1.2
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"   

def():
      above:
           iteration=true:
                         pass:
version: 0.1.3
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"     

def():
      above:
           iteration=true:
                         pass:
version: 0.1.4
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"  

def():
      above:
           iteration=true:
                         pass:
version: 0.1.5
updates:
  - package-ecosystem: "TBTS-PVT-LTD" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule: "12:00 pm"
      interval: "weekly"                       
